CREATE TABLE IPV4_ILINES
(
IPV4_SERVER_NAME VARCHAR(50),
IPV4_NETWORK_START  DECIMAL(50),
IPV4_NETWORK_STOP DECIMAL(50),
IPV4_MASK VARCHAR(25),
IPV4_CCTLD VARCHAR(10),
IPV4_TLD VARCHAR(20),
IPV4_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY
);


CREATE TABLE IPV6_ILINES
(
IPV6_SERVER_NAME VARCHAR(50) ,
IPV6_NETWORK_START  DECIMAL(50),
IPV6_NETWORK_STOP  DECIMAL(50),
IPV6_MASK VARCHAR(100),
IPV6_CCTLD VARCHAR(10),
IPV6_TLD VARCHAR(20),
IPV6_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE STATS
(
STATS_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
STATS_QUERY  DECIMAL(30)
);


CREATE INDEX IDX_IPV4_STAR ON IPV4_ILINES (IPV4_NETWORK_START);
CREATE INDEX IDX_IPV4_STOP ON IPV4_ILINES (IPV4_NETWORK_STOP);
CREATE INDEX IDX_IPV6_STAR ON IPV6_ILINES (IPV6_NETWORK_START);
CREATE INDEX IDX_IPV6_STOP ON IPV6_ILINES (IPV6_NETWORK_STOP);
CREATE INDEX IDX_STATS ON STATS (STATS_QUERY);
