truncate IPV4_ILINES;
truncate IPV6_ILINES;
LOAD DATA LOCAL INFILE '/home/iline/import/IPV4_FILE.db' INTO TABLE IPV4_ILINES COLUMNS TERMINATED BY '|';
LOAD DATA LOCAL INFILE '/home/iline/import/IPV6_FILE.db' INTO TABLE IPV6_ILINES COLUMNS TERMINATED BY '|';
DELETE n1 FROM IPV6_ILINES n1, IPV6_ILINES n2 WHERE n1.IPV6_ID > n2.IPV6_ID AND n1.IPV6_SERVER_NAME = n2.IPV6_SERVER_NAME AND n1.IPV6_NETWORK_START = n2.IPV6_NETWORK_START AND n1.IPV6_NETWORK_STOP = n2.IPV6_NETWORK_STOP;
DELETE n1 FROM IPV4_ILINES n1, IPV4_ILINES n2 WHERE n1.IPV4_ID > n2.IPV4_ID AND n1.IPV4_SERVER_NAME = n2.IPV4_SERVER_NAME AND n1.IPV4_NETWORK_START = n2.IPV4_NETWORK_START AND n1.IPV4_NETWORK_STOP = n2.IPV4_NETWORK_STOP;
delete from IPV4_ILINES where IPV4_SERVER_NAME='irc.nebula.fi' and IPV4_MASK='0.0.0.0/0';
delete from IPV4_ILINES where IPV4_SERVER_NAME='atw.irc.hu' and IPV4_MASK='0.0.0.0/0';
delete from IPV4_ILINES where IPV4_SERVER_NAME='irc.home.uit.no' and IPV4_MASK='0.0.0.0/1';
delete from IPV4_ILINES where IPV4_SERVER_NAME='ssl.atw.irc.hu' and IPV4_MASK='0.0.0.0/0';
delete from IPV4_ILINES where IPV4_SERVER_NAME='irc.nfx.cz' and IPV4_MASK='0.0.0.0/0';
delete from IPV4_ILINES where IPV4_SERVER_NAME='irc.nfx.cz' and IPV4_MASK='128.0.0.0/1';
delete from IPV6_ILINES where IPV6_SERVER_NAME='irc.arnes.si' and IPV6_MASK='::/0';
delete from IPV6_ILINES where IPV6_SERVER_NAME='irc.nebula.fi' and IPV6_MASK='2a00::/8';
delete from IPV4_ILINES where IPV4_SERVER_NAME='irc.nfx.cz' and IPV4_MASK='0.0.0.0/1';
delete from IPV6_ILINES where IPV6_SERVER_NAME='irc.nebula.fi' and IPV6_MASK='2001::/16';
delete from IPV6_ILINES where IPV6_SERVER_NAME='ircd.seed.net.tw' and IPV6_MASK='::/1';
delete from IPV6_ILINES where IPV6_SERVER_NAME='irc.home.uit.no' and IPV6_MASK='::/1';
delete from IPV6_ILINES where IPV6_SERVER_NAME='irc.nebula.fi' and IPV6_MASK='2001::/16';
delete from IPV4_ILINES where IPV4_SERVER_NAME='irc.nfx.cz' and IPV4_MASK='128.0.0.0/1';
delete from IPV4_ILINES where IPV4_SERVER_NAME='eu.irc6.net' and IPV4_MASK='0.0.0.0/0';
delete from IPV4_ILINES where IPV4_SERVER_NAME='ircd.seed.net.tw' and IPV4_MASK='0.0.0.0/1';
DELETE from IPV6_ILINES where IPV6_SERVER_NAME='irc.nlnog.net';
update IPV4_ILINES set IPV4_SERVER_NAME='irc.belwue.de' where IPV4_SERVER_NAME='belwue.de';
update IPV4_ILINES set IPV4_SERVER_NAME='irc.fu-berlin.de' where IPV4_SERVER_NAME='fu-berlin.de';
update IPV4_ILINES set IPV4_SERVER_NAME='irc.man-da.de' where IPV4_SERVER_NAME='MAN-DA.DE';
update IPV4_ILINES set IPV4_SERVER_NAME='irc.in.tum.de' where IPV4_SERVER_NAME='TUM.DE';
update IPV4_ILINES set IPV4_SERVER_NAME='irc.uni-erlangen.de' where IPV4_SERVER_NAME='uni-erlangen.de';
update IPV6_ILINES set IPV6_SERVER_NAME='irc.uni-erlangen.de' where IPV6_SERVER_NAME='uni-erlangen.de';
update IPV6_ILINES set IPV6_SERVER_NAME='irc.belwue.de' where IPV6_SERVER_NAME='belwue.de';
update IPV6_ILINES set IPV6_SERVER_NAME='irc.man-da.de' where IPV6_SERVER_NAME='MAN-DA.DE';
COMMIT;

